# Generated by Django 5.2.2 on 2025-06-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_type', models.CharField(max_length=20)),
                ('screw_length', models.PositiveIntegerField()),
                ('angle', models.PositiveIntegerField()),
                ('capacity_perpendicular', models.PositiveIntegerField()),
                ('capacity_milling', models.PositiveIntegerField()),
                ('capacity_inclined', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_type', models.CharField(max_length=20)),
                ('screw_length', models.PositiveIntegerField()),
                ('angle', models.PositiveIntegerField()),
                ('capacity_perpendicular', models.PositiveIntegerField()),
                ('capacity_milling', models.PositiveIntegerField()),
                ('capacity_inclined', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_type', models.CharField(max_length=20)),
                ('screw_length', models.PositiveIntegerField()),
                ('angle', models.PositiveIntegerField()),
                ('capacity_perpendicular', models.PositiveIntegerField()),
                ('capacity_milling', models.PositiveIntegerField()),
                ('capacity_inclined', models.PositiveIntegerField()),
            ],
        ),
    ]
